run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - revive
    - misspell

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
  exclude-generated: strict
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - staticcheck
      text: "SA1019: grpc\\.(DialContext|WithBlock)"
